version: '3'
services:
  api-server:
    image: api-v1.0.0
    environment:
      # Node environment
      - NODE_ENV=development
      # Port number
      - PORT=8810
      # URL of the Mongo DB
      - MONGODB_URL=mongodb://mongo:27017/what-to-cook-app
      - CLIENT_URL=http://localhost:3000
      - BASE_URL=http://localhost:8810/api
      # JWT secret key
      - JWT_SECRET=asdasdasdasdasdasdasdasdasd
      # Number of minutes after which an access token expires
      - JWT_ACCESS_EXPIRATION_MINUTES=5
      # Number of days after which a refresh token expires
      - JWT_REFRESH_EXPIRATION_DAYS=30
      # Number of minutes after which a reset password token expires
      - JWT_RESET_PASSWORD_EXPIRATION_MINUTES=10
      # Number of minutes after which a verify email token expires
      - JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=10
      # SMTP configuration options for the email service
      # For testing, you can use a fake SMTP service like Ethereal: https://ethereal.email/create
      - SMTP_HOST=smtp.ethereal.email
      - SMTP_PORT=587
      - SMTP_USERNAME=jacky87@ethereal.email
      - SMTP_PASSWORD=zFcFW5VYeqpKzrQU9p
      - EMAIL_FROM=rado_test@ethereal.email
    ports:
      - "8810:8810"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=what-to-cook-app
    volumes:
      - ./mongo-seed.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"

  client:
    image: what-to-cook-client
    ports:
      - "3000:3000"
    command: npm start
