db = db.getSiblingDB('what-to-cook-app');

db.createCollection('products');

db.products.insertMany([
    { name: 'Домати', measurementUnit: 'килограм' },
    { name: 'Лук', measurementUnit: 'килограм' },
    { name: 'Картофи', measurementUnit: 'килограм' },
    { name: 'Моркови', measurementUnit: 'килограм' },
    { name: 'Чесън', measurementUnit: 'брой' },
    { name: 'Пилешко месо', measurementUnit: 'килограм' },
    { name: 'Свинско месо', measurementUnit: 'килограм' },
    { name: 'Яйца', measurementUnit: 'брой' },
    { name: 'Мляко', measurementUnit: 'литър' },
    { name: 'Сирене', measurementUnit: 'килограм' },
    { name: 'Кашкавал', measurementUnit: 'килограм' },
    { name: 'Брашно', measurementUnit: 'килограм' },
    { name: 'Олио', measurementUnit: 'литър' },
    { name: 'Ориз', measurementUnit: 'килограм' },
    { name: 'Захар', measurementUnit: 'килограм' },
    { name: 'Сол', measurementUnit: 'грам' },
    { name: 'Черен пипер', measurementUnit: 'грам' },
    { name: 'Оцет', measurementUnit: 'милилитър' },
    { name: 'Лимон', measurementUnit: 'брой' },
    { name: 'Магданоз', measurementUnit: 'брой' },
    { name: 'Чушки', measurementUnit: 'килограм' },
    { name: 'Краставици', measurementUnit: 'килограм' },
    { name: 'Тиквички', measurementUnit: 'килограм' },
    { name: 'Патладжан', measurementUnit: 'килограм' },
    { name: 'Спанак', measurementUnit: 'килограм' },
    { name: 'Гъби', measurementUnit: 'килограм' },
    { name: 'Телешко месо', measurementUnit: 'килограм' },
    { name: 'Риба', measurementUnit: 'килограм' },
    { name: 'Кисело мляко', measurementUnit: 'брой' },
    { name: 'Масло', measurementUnit: 'грам' },
    { name: 'Сметана', measurementUnit: 'милилитър' },
    { name: 'Макарони', measurementUnit: 'грам' },
    { name: 'Зехтин', measurementUnit: 'милилитър' },
    { name: 'Боб', measurementUnit: 'килограм' },
    { name: 'Леща', measurementUnit: 'килограм' },
    { name: 'Нахут', measurementUnit: 'килограм' },
    { name: 'Червен пипер', measurementUnit: 'грам' },
    { name: 'Копър', measurementUnit: 'брой' },
    { name: 'Босилек', measurementUnit: 'брой' },
    { name: 'Чубрица', measurementUnit: 'грам' },
    { name: 'Ябълки', measurementUnit: 'килограм' },
    { name: 'Банани', measurementUnit: 'килограм' },
    { name: 'Портокали', measurementUnit: 'килограм' },
    { name: 'Грозде', measurementUnit: 'килограм' },
    { name: 'Круши', measurementUnit: 'килограм' },
    { name: 'Праскови', measurementUnit: 'килограм' },
    { name: 'Кайсии', measurementUnit: 'килограм' },
    { name: 'Череши', measurementUnit: 'килограм' },
    { name: 'Сливи', measurementUnit: 'килограм' },
    { name: 'Ягоди', measurementUnit: 'килограм' },
    { name: 'Малини', measurementUnit: 'грам' },
    { name: 'Боровинки', measurementUnit: 'грам' },
    { name: 'Авокадо', measurementUnit: 'брой' },
    { name: 'Ананас', measurementUnit: 'брой' },
    { name: 'Манго', measurementUnit: 'брой' },
    { name: 'Киви', measurementUnit: 'брой' },
    { name: 'Нар', measurementUnit: 'брой' },
    { name: 'Диня', measurementUnit: 'брой' },
    { name: 'Пъпеш', measurementUnit: 'брой' },
    { name: 'Тиква', measurementUnit: 'килограм' },
    { name: 'Броколи', measurementUnit: 'килограм' },
    { name: 'Карфиол', measurementUnit: 'килограм' },
    { name: 'Зеле', measurementUnit: 'килограм' },
    { name: 'Марули', measurementUnit: 'брой' },
    { name: 'Рукола', measurementUnit: 'грам' },
    { name: 'Целина', measurementUnit: 'брой' },
    { name: 'Репички', measurementUnit: 'връзка' },
    { name: 'Ряпа', measurementUnit: 'килограм' },
    { name: 'Цвекло', measurementUnit: 'килограм' },
    { name: 'Аспержи', measurementUnit: 'връзка' },
    { name: 'Артишок', measurementUnit: 'брой' },
    { name: 'Бамя', measurementUnit: 'килограм' },
    { name: 'Грах', measurementUnit: 'килограм' },
    { name: 'Зелен фасул', measurementUnit: 'килограм' },
    { name: 'Червен боб', measurementUnit: 'килограм' },
    { name: 'Черен боб', measurementUnit: 'килограм' },
    { name: 'Соя', measurementUnit: 'грам' },
    { name: 'Киноа', measurementUnit: 'грам' },
    { name: 'Булгур', measurementUnit: 'грам' },
    { name: 'Кускус', measurementUnit: 'грам' },
    { name: 'Овесени ядки', measurementUnit: 'грам' },
    { name: 'Елда', measurementUnit: 'грам' },
    { name: 'Просо', measurementUnit: 'грам' },
    { name: 'Ечемик', measurementUnit: 'грам' },
    { name: 'Ръж', measurementUnit: 'грам' },
    { name: 'Пшеница', measurementUnit: 'килограм' },
    { name: 'Царевично брашно', measurementUnit: 'килограм' },
    { name: 'Пълнозърнесто брашно', measurementUnit: 'килограм' },
    { name: 'Типово брашно', measurementUnit: 'килограм' },
    { name: 'Ръжено брашно', measurementUnit: 'килограм' },
    { name: 'Оризово брашно', measurementUnit: 'грам' },
    { name: 'Бадемово брашно', measurementUnit: 'грам' },
    { name: 'Кокосово брашно', measurementUnit: 'грам' },
    { name: 'Нишесте', measurementUnit: 'грам' },
    { name: 'Бакпулвер', measurementUnit: 'грам' },
    { name: 'Сода за хляб', measurementUnit: 'грам' },
    { name: 'Мая', measurementUnit: 'грам' },
    { name: 'Какао', measurementUnit: 'грам' },
    { name: 'Шоколад', measurementUnit: 'грам' },
    { name: 'Ванилия', measurementUnit: 'брой' },
    { name: 'Канела', measurementUnit: 'грам' },
    { name: 'Джинджифил', measurementUnit: 'грам' },
    { name: 'Кардамон', measurementUnit: 'грам' },
    { name: 'Куркума', measurementUnit: 'грам' },
    { name: 'Кориандър', measurementUnit: 'грам' },
    { name: 'Кимион', measurementUnit: 'грам' },
    { name: 'Риган', measurementUnit: 'грам' },
    { name: 'Мащерка', measurementUnit: 'грам' },
    { name: 'Розмарин', measurementUnit: 'грам' },
    { name: 'Салвия', measurementUnit: 'грам' },
    { name: 'Мента', measurementUnit: 'връзка' },
    { name: 'Лайка', measurementUnit: 'грам' },
    { name: 'Лавандула', measurementUnit: 'грам' },
    { name: 'Дафинов лист', measurementUnit: 'брой' },
    { name: 'Индийско орехче', measurementUnit: 'грам' },
    { name: 'Шафран', measurementUnit: 'грам' },
    { name: 'Чили', measurementUnit: 'брой' },
    { name: 'Пушен пипер', measurementUnit: 'грам' },
    { name: 'Къри', measurementUnit: 'грам' },
    { name: 'Горчица', measurementUnit: 'грам' },
    { name: 'Хрян', measurementUnit: 'грам' },
    { name: 'Чесън на прах', measurementUnit: 'грам' },
    { name: 'Лук на прах', measurementUnit: 'грам' },
    { name: 'Целина на прах', measurementUnit: 'грам' },
    { name: 'Джоджен', measurementUnit: 'грам' },
    { name: 'Сминдух', measurementUnit: 'грам' },
    { name: 'Бахар', measurementUnit: 'грам' },
    { name: 'Карамфил', measurementUnit: 'грам' },
    { name: 'Анасон', measurementUnit: 'грам' },
    { name: 'Копър семе', measurementUnit: 'грам' },
    { name: 'Кимион семе', measurementUnit: 'грам' },
    { name: 'Сусам', measurementUnit: 'грам' },
    { name: 'Мак', measurementUnit: 'грам' },
    { name: 'Чия', measurementUnit: 'грам' },
    { name: 'Лен', measurementUnit: 'грам' },
    { name: 'Тиквени семки', measurementUnit: 'грам' },
    { name: 'Слънчогледови семки', measurementUnit: 'грам' },
    { name: 'Кашу', measurementUnit: 'грам' },
    { name: 'Бадеми', measurementUnit: 'грам' },
    { name: 'Лешници', measurementUnit: 'грам' },
    { name: 'Орехи', measurementUnit: 'грам' },
    { name: 'Фъстъци', measurementUnit: 'грам' },
    { name: 'Шам фъстък', measurementUnit: 'грам' },
    { name: 'Кокос', measurementUnit: 'грам' },
    { name: 'Стафиди', measurementUnit: 'грам' },
    { name: 'Сушени кайсии', measurementUnit: 'грам' },
    { name: 'Сушени смокини', measurementUnit: 'грам' },
    { name: 'Сушени сливи', measurementUnit: 'грам' },
    { name: 'Фурми', measurementUnit: 'грам' },
    { name: 'Годжи бери', measurementUnit: 'грам' },
    { name: 'Мед', measurementUnit: 'грам' },
    { name: 'Кленов сироп', measurementUnit: 'милилитър' },
    { name: 'Агаве сироп', measurementUnit: 'милилитър' },
    { name: 'Кафява захар', measurementUnit: 'грам' },
    { name: 'Пудра захар', measurementUnit: 'грам' },
    { name: 'Стевия', measurementUnit: 'грам' },
    { name: 'Кетчуп', measurementUnit: 'грам' },
    { name: 'Майонеза', measurementUnit: 'грам' },
    { name: 'Соев сос', measurementUnit: 'милилитър' },
    { name: 'Рибен сос', measurementUnit: 'милилитър' },
    { name: 'Уорчестър сос', measurementUnit: 'милилитър' },
    { name: 'Табаско', measurementUnit: 'милилитър' },
    { name: 'Балсамов оцет', measurementUnit: 'милилитър' },
    { name: 'Ябълков оцет', measurementUnit: 'милилитър' },
    { name: 'Оризов оцет', measurementUnit: 'милилитър' },
    { name: 'Вино бяло', measurementUnit: 'милилитър' },
    { name: 'Вино червено', measurementUnit: 'милилитър' },
    { name: 'Коняк', measurementUnit: 'милилитър' },
    { name: 'Ром', measurementUnit: 'милилитър' },
    { name: 'Водка', measurementUnit: 'милилитър' },
    { name: 'Бира', measurementUnit: 'милилитър' },
    { name: 'Сода', measurementUnit: 'литър' },
    { name: 'Минерална вода', measurementUnit: 'литър' },
    { name: 'Кафе', measurementUnit: 'грам' },
    { name: 'Чай', measurementUnit: 'брой' },
    { name: 'Какао на прах', measurementUnit: 'грам' },
    { name: 'Кокосово мляко', measurementUnit: 'милилитър' },
    { name: 'Бадемово мляко', measurementUnit: 'милилитър' },
    { name: 'Соево мляко', measurementUnit: 'милилитър' },
    { name: 'Оризово мляко', measurementUnit: 'милилитър' },
    { name: 'Сладолед', measurementUnit: 'литър' },
    { name: 'Маргарин', measurementUnit: 'грам' },
    { name: 'Крема сирене', measurementUnit: 'грам' },
    { name: 'Рикота', measurementUnit: 'грам' },
    { name: 'Моцарела', measurementUnit: 'грам' },
    { name: 'Пармезан', measurementUnit: 'грам' },
    { name: 'Чедър', measurementUnit: 'грам' },
    { name: 'Фета', measurementUnit: 'грам' },
    { name: 'Халуми', measurementUnit: 'грам' },
    { name: 'Козе сирене', measurementUnit: 'грам' },
    { name: 'Синьо сирене', measurementUnit: 'грам' },
    { name: 'Извара', measurementUnit: 'грам' },
    { name: 'Заквасена сметана', measurementUnit: 'грам' },
    { name: 'Течна сметана', measurementUnit: 'милилитър' },
    { name: 'Кондензирано мляко', measurementUnit: 'грам' },
    { name: 'Кокосова сметана', measurementUnit: 'милилитър' },
    { name: 'Тофу', measurementUnit: 'грам' },
    { name: 'Темпе', measurementUnit: 'грам' },
    { name: 'Сейтан', measurementUnit: 'грам' },
    { name: 'Хумус', measurementUnit: 'грам' },
    { name: 'Тахан', measurementUnit: 'грам' },
    { name: 'Фъстъчено масло', measurementUnit: 'грам' },
    { name: 'Бадемово масло', measurementUnit: 'грам' },
    { name: 'Кокосово масло', measurementUnit: 'грам' },
    { name: 'Гхи', measurementUnit: 'грам' },
    { name: 'Рапично олио', measurementUnit: 'милилитър' },
    { name: 'Слънчогледово олио', measurementUnit: 'милилитър' },
    { name: 'Тиквено олио', measurementUnit: 'милилитър' },
    { name: 'Ленено олио', measurementUnit: 'милилитър' },
    { name: 'Фъстъчено олио', measurementUnit: 'милилитър' },
    { name: 'Авокадо олио', measurementUnit: 'милилитър' },
    { name: 'Пилешки гърди', measurementUnit: 'килограм' },
    { name: 'Кисели краставички', measurementUnit: 'брой' },
    { name: 'Царевица', measurementUnit: 'брой' },
    { name: 'Сусамово олио', measurementUnit: 'милилитър' },
    { name: 'Червена леща', measurementUnit: 'грам' },
    { name: 'Чери домати', measurementUnit: 'килограм' },
    { name: 'Пушена сьомга', measurementUnit: 'грам' },
    { name: 'Кокосови стърготини', measurementUnit: 'грам' },
    { name: 'Сушени домати', measurementUnit: 'грам' },
    { name: 'Кейл', measurementUnit: 'връзка' },
    { name: 'Червено цвекло', measurementUnit: 'килограм' },
    { name: 'Пилешки бутчета', measurementUnit: 'килограм' },
    { name: 'Пилешки крилца', measurementUnit: 'килограм' },
    { name: 'Пилешки дробчета', measurementUnit: 'килограм' },
    { name: 'Пилешки воденички', measurementUnit: 'килограм' },
    { name: 'Пилешка кайма', measurementUnit: 'килограм' },
    { name: 'Пилешки шницел', measurementUnit: 'килограм' },
    { name: 'Пилешки хапки', measurementUnit: 'килограм' },
    { name: 'Пилешки филе', measurementUnit: 'килограм' },
    { name: 'Пилешки гърди без кост', measurementUnit: 'килограм' },
    { name: 'Цяло пиле', measurementUnit: 'килограм' },
    { name: 'Свински котлет', measurementUnit: 'килограм' },
    { name: 'Свински врат', measurementUnit: 'килограм' },
    { name: 'Свински ребра', measurementUnit: 'килограм' },
    { name: 'Свинска плешка', measurementUnit: 'килограм' },
    { name: 'Свинска кайма', measurementUnit: 'килограм' },
    { name: 'Свински бут', measurementUnit: 'килограм' },
    { name: 'Свински джолан', measurementUnit: 'килограм' },
    { name: 'Свински пържоли', measurementUnit: 'килограм' },
    { name: 'Свинско филе', measurementUnit: 'килограм' },
    { name: 'Свински шницел', measurementUnit: 'килограм' },
    { name: 'Бекон', measurementUnit: 'грам' },
    { name: 'Панчета', measurementUnit: 'грам' },
    { name: 'Прошуто', measurementUnit: 'грам' },
    { name: 'Шунка', measurementUnit: 'грам' },
    { name: 'Салам', measurementUnit: 'грам' },
]);